[package]
name = "roll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
irc = "0.15.0"
log = "0.4.20"
rand = { version = "0.8.5", features = [ "small_rng" ] }
simple_logger = "4.3.3"
tokio = { version = "1.36.0", features = ["full"] }
